# outgoing:ingoing

version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports: 
      - "80:80"
    restart: always
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    build: ./server
    ports:
      - '7001:7001'
    restart: always

  frontend:
    container_name: frontend
    build: ./client
    ports:
      - '7002:7002'
    restart: always
